# Create the CustomerResourceDefinition for MongoDB custom types.
createCrds: true

# Name of the Namespace to use
namespace: mongodb

# Set this to true if your cluster is managing SecurityContext for you.
# If running OpenShift (Cloud, Minishift, etc.), set this to true.
managedSecurityContext: false

operator:
  # Execution environment for the operator, dev or prod. Use dev for more verbose logging
  env: prod

  # Name that will be assigned to most of internal Kubernetes objects like Deployment, ServiceAccount, Role etc.
  name: mongodb-enterprise-operator

  # Version of mongodb-enterprise-operator and mongodb-enterprise-database images
  version: 1.2.4

database:
  name: mongodb-enterprise-database

opsManager:
  name: mongodb-enterprise-ops-manager

registry:
  # Specify if images are pulled from private repository
  imagePullSecrets:
  pullPolicy: IfNotPresent
  #repository: quay.io/mongodb
  repository: quay-mirror.qiniu.com/mongodb

# Set this to true if the operator will require Kubernetes CA
# infrastructure to generate TLS certificates.
needsCAInfrastructure: true

mms:
  projectName: replicaSet
  orgId: 5d86c36c82c6a72ac22bd1d1
  baseUrl: http://192.168.1.9:8080
  #private key of mms project
  user: MYWNRACR
  publicApiKey: 9329fe7b-b778-4106-a99e-f41f90e30553
  #for configmap enabling x509
  clusterAuthenticationMode: x509

# type: Standalone
type: ReplicaSet
# type: ShardedCluster

# Standalone:
#   version: 4.2.0

#   persistent: true

#   podSpec:
#     cpu: '0.2'
#     memory: 512M
#     persistence:
#       multiple:
#         # if the child of "multiple" is omitted then the default size will be used.
#         # 16G for "data", 1G for "journal", 3Gb for "logs"
#         data:
#           storage: 1G
#           storageClass: standard
#         logs:
#           storage: 500M
#           storageClass: standard

ReplicaSet:
  version: 4.2.0

  members: 3

  persistent: true

  podSpec:
    cpu: '0.2'
    memory: 512M
    persistence:
      multiple:
        # if the child of "multiple" is omitted then the default size will be used.
        # 16G for "data", 1G for "journal", 3Gb for "logs"
        data:
          storage: 1G
          storageClass: standard
        logs:
          storage: 500M
          storageClass: standard

  security:
    clusterAuthenticationMode: x509
    tls:
      enabled: true

  additionalMongodConfig:
    net:
      ssl:
        mode: "preferSSL"


# ShardedCluster:
#   shardCount: 2
#   mongodsPerShardCount: 3
#   mongosCount: 1
#   configServerCount: 3

#   version: 4.2.0

#   persistent: true

#   configSrvPodSpec:
#     cpu: '0.2'
#     memory: 512M
#     persistence:
#       single:
#         storage: 1G
#         storageClass: standard

#   mongosPodSpec:
#     cpu: '0.2'
#     memory: 512M

#   shardPodSpec:
#     cpu: '0.2'
#     memory: 512M
#     persistence:
#       multiple:
#         # if the child of "multiple" is omitted then the default size will be used.
#         # 16G for "data", 1G for "journal", 3Gb for "logs"
#         data:
#           storage: 1G
#           storageClass: standard
#         logs:
#           storage: 500M
#           storageClass: standard

#   security:
#     clusterAuthenticationMode: x509
#     tls:
#       enabled: true

#   additionalMongodConfig:
#     net:
#       ssl:
#         mode: "preferSSL"
