---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mongodb-database.project" . }}
data:
  projectName: {{ .Values.mms.projectName }}
  orgId: {{ .Values.mms.orgId }}
  baseUrl: {{ .Values.mms.baseUrl }}