#
# This is a minimal config. To see all the options available, refer to the
# "extended" directory
#
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set
spec:
  members: 3
  version: 4.2.0
  type: ReplicaSet

  project: {{ template "mongodb-database.project" . }}
  credentials: {{ template "mongodb-database.credentials" . }}

  persistent: false

  security:
    tls:
      enabled: true

  additionalMongodConfig:
    net:
      ssl:
        mode: "preferSSL"
