---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mongodb-database.credentials" . }}
type: Opaque
data:
  user: {{ .Values.mms.user | b64enc }}
  publicApiKey: {{ .Values.mms.publicApiKey | b64enc }}