---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-sharded-cluster
spec:
  type: ShardedCluster

  shardCount: 2
  mongodsPerShardCount: 3
  mongosCount: 1
  configServerCount: 3

  version: 4.0.6

  project: my-project
  credentials: my-credentials

  persistent: true
  configSrvPodSpec:
    cpu: '0.2'
    memory: 512M
    persistence:
      single:
        storage: 1G

  mongosPodSpec:
    cpu: '0.2'
    memory: 512M
    persistence:
      single:
        storage: 1G

  shardPodSpec:
    cpu: '0.2'
    memory: 512M
    persistence:
      multiple:
        # if the child of "multiple" is omitted then the default size will be used.
        # 16G for "data", 1G for "journal", 3Gb for "logs"
        data:
          storage: 1G
        logs:
          storage: 500M
          storageClass: standard


security:
    clusterAuthenticationMode: x509
    tls:
      enabled: true