---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-sharded-cluster
spec:
  type: ShardedCluster

  shardCount: 2
  mongodsPerShardCount: 3
  mongosCount: 2
  configServerCount: 3

  version: 4.0.6

  project: my-project
  credentials: my-credentials

  persistent: false
