---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: mongodba
spec:
  username: "CN=my-x509-authenticated-user, OU=organizationalunit, O=organization"
  db: "$external"
  project: my-project
  roles:
    - db: "admin"
      name: "root"