---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: new-x509-user
spec:
  username: "CN=my-x509-authenticated-user, OU=organizationalunit, O=organization"
  db: "$external"
  project: {{ template "mongodb-database.project" . }}
  roles:
    - db: "admin"
      name: "root"